title: Neostore Website
description: Content management for Neostore website

collections:
  - name: homepage
    label: Homepage Content
    files:
      - name: hero
        label: Hero Section
        file: content/hero.json
        fields:
          - name: title_hr
            label: Title (Croatian)
            widget: string
          - name: title_en
            label: Title (English)
            widget: string
          - name: subtitle_hr
            label: Subtitle (Croatian)
            widget: text
          - name: subtitle_en
            label: Subtitle (English)
            widget: text
          - name: badge_hr
            label: Badge Text (Croatian)
            widget: string
          - name: badge_en
            label: Badge Text (English)
            widget: string
      
      - name: web_section
        label: Web Development Section
        file: content/web.json
        fields:
          - name: title_hr
            label: Section Title (Croatian)
            widget: string
          - name: title_en
            label: Section Title (English)
            widget: string
          - name: subtitle_hr
            label: Subtitle (Croatian)
            widget: text
          - name: subtitle_en
            label: Subtitle (English)
            widget: text
          - name: heading_hr
            label: Heading (Croatian)
            widget: string
          - name: heading_en
            label: Heading (English)
            widget: string
          - name: description_hr
            label: Description (Croatian)
            widget: text
          - name: description_en
            label: Description (English)
            widget: text
      
      - name: ai_section
        label: AI Solutions Section
        file: content/ai.json
        fields:
          - name: title_hr
            label: Section Title (Croatian)
            widget: string
          - name: title_en
            label: Section Title (English)
            widget: string
          - name: subtitle_hr
            label: Subtitle (Croatian)
            widget: text
          - name: subtitle_en
            label: Subtitle (English)
            widget: text
          - name: heading_hr
            label: Heading (Croatian)
            widget: string
          - name: heading_en
            label: Heading (English)
            widget: string
          - name: description_hr
            label: Description (Croatian)
            widget: text
          - name: description_en
            label: Description (English)
            widget: text
      
      - name: telecom_section
        label: Telecommunications Section
        file: content/telecom.json
        fields:
          - name: title_hr
            label: Section Title (Croatian)
            widget: string
          - name: title_en
            label: Section Title (English)
            widget: string
          - name: b2b_title_hr
            label: B2B Services Title (Croatian)
            widget: string
          - name: b2b_title_en
            label: B2B Services Title (English)
            widget: string
          - name: service_title_hr
            label: Device Service Title (Croatian)
            widget: string
          - name: service_title_en
            label: Device Service Title (English)
            widget: string
      
      - name: business_section
        label: Business Planning Section
        file: content/business.json
        fields:
          - name: title_hr
            label: Section Title (Croatian)
            widget: string
          - name: title_en
            label: Section Title (English)
            widget: string
      
      - name: contact_section
        label: Contact Section
        file: content/contact.json
        fields:
          - name: title_hr
            label: Section Title (Croatian)
            widget: string
          - name: title_en
            label: Section Title (English)
            widget: string

      - name: settings
        label: Site Settings
        file: content/settings.json
        fields:
          - name: site_title
            label: Site Title
            widget: string
          - name: site_description
            label: Site Description
            widget: text
          - name: contact_phone
            label: Contact Phone
            widget: string
          - name: contact_email
            label: Contact Email
            widget: string
          - name: contact_address
            label: Contact Address
            widget: string
          - name: logo
            label: Logo Image
            widget: image

media_folder: "."
public_folder: "/"
